# Generated by Django 2.1.3 on 2018-12-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0003_auto_20181205_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_boleta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
