# Generated by Django 2.1.3 on 2018-12-05 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0004_auto_20181205_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Venta'),
        ),
    ]
