# Generated by Django 2.1.3 on 2018-12-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0006_boleta_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='encargado',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
