# Generated by Django 2.1.3 on 2018-12-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0007_tienda_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_boleta',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
