# Generated by Django 2.1.3 on 2018-12-05 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0008_auto_20181205_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicativo.Tienda'),
            preserve_default=False,
        ),
    ]
