# Generated by Django 2.1.3 on 2018-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0009_producto_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tienda',
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ManyToManyField(to='aplicativo.Tienda'),
        ),
    ]
