# Generated by Django 2.1.3 on 2018-12-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0010_auto_20181205_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tienda',
        ),
    ]
